import { Montserrat } from "@next/font/google";
import "../styles/tailwind-globals.css";
export const metadata = {
  title: "Agustin Cristobo - Portfolio",
  description: "Generated by Next.js",
};
import { Navigator } from "../components";
import { Routes } from "../models";

const monserrat = Montserrat({
  weight: ["400", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"],
  variable: "--font-monserrat",
  display: "optional",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={monserrat.className}>
      <body>
        <Navigator pathNames={[Routes.HOME, Routes.ABOUT, Routes.PROJECTS]} />

        {children}
      </body>
    </html>
  );
}
