export { default as About } from "./About/About";
export { default as Card } from "./Card/Card";
export { default as Footer } from "./Footer/Footer";
export { default as Loader } from "./Loader/Loader";
export { default as Navigator } from "./Navigator/Navigator";
export { default as Projects } from "./Projects/Projects";
export { default as ScrollButton } from "./ScrollButton/ScrollButton";
export { default as ScrollLink } from "./ScrollLink/ScrollLink";
export { default as Welcome } from "./Welcome/Welcome";
